name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup tools
      run: sudo apt-get -y install gcc-arm-linux-gnueabihf device-tree-compiler bison flex
    - name: config
      run: make snappermx6_defconfig CROSS_COMPILE=arm-linux-gnueabihf-
    - name: build
      run: make -j u-boot.imx CROSS_COMPILE=arm-linux-gnueabihf-
    - name: save output
      run: mkdir -p release && cp -a u-boot.bin u-boot.imx u-boot-with-spl.imx u-boot release/
    - uses: actions/upload-artifact@v1
      with:
        name: Binaries
        path: release
